// Dark sleek theme - shared across all pages
const T = {
  // Colors
  bg: "#0f0f0f",
  bgCard: "#1a1a1a",
  bgCardHover: "#222",
  bgSidebar: "#111",
  bgInput: "#1e1e1e",
  bgModal: "rgba(0,0,0,0.7)",
  border: "#2a2a2a",
  borderLight: "#333",
  text: "#e5e5e5",
  textMuted: "#888",
  textDim: "#666",
  accent: "#fff",
  accentSoft: "rgba(255,255,255,0.08)",
  accentBorder: "rgba(255,255,255,0.15)",
  green: "#22c55e",
  greenSoft: "rgba(34,197,94,0.12)",
  red: "#ef4444",
  redSoft: "rgba(239,68,68,0.12)",
  yellow: "#eab308",
  yellowSoft: "rgba(234,179,8,0.12)",
  blue: "#3b82f6",
  blueSoft: "rgba(59,130,246,0.12)",
  purple: "#a78bfa",
  purpleSoft: "rgba(167,139,250,0.12)",
  orange: "#f97316",
  orangeSoft: "rgba(249,115,22,0.12)",

  // Styles
  card: {
    background: "#1a1a1a",
    borderRadius: 10,
    border: "1px solid #2a2a2a",
    padding: "1.5rem",
    marginBottom: "1rem",
  },
  input: {
    padding: "0.6rem 0.9rem",
    fontSize: "0.9rem",
    border: "1px solid #333",
    borderRadius: 8,
    outline: "none",
    background: "#1e1e1e",
    color: "#e5e5e5",
    width: "100%",
  },
  select: {
    padding: "0.6rem 0.9rem",
    fontSize: "0.9rem",
    border: "1px solid #333",
    borderRadius: 8,
    outline: "none",
    background: "#1e1e1e",
    color: "#e5e5e5",
  },
  btn: (bg = "#fff", fg = "#000") => ({
    padding: "0.6rem 1.2rem",
    fontSize: "0.85rem",
    fontWeight: 600,
    color: fg,
    background: bg,
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    letterSpacing: "0.02em",
  }),
  btnSm: (bg = "#fff", fg = "#000") => ({
    padding: "0.35rem 0.75rem",
    fontSize: "0.78rem",
    fontWeight: 600,
    color: fg,
    background: bg,
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  }),
  btnOutline: (color = "#888") => ({
    padding: "0.35rem 0.75rem",
    fontSize: "0.78rem",
    fontWeight: 600,
    color,
    background: "transparent",
    border: `1px solid ${color}`,
    borderRadius: 6,
    cursor: "pointer",
  }),
  btnDisabled: { opacity: 0.4, cursor: "not-allowed" },
  badge: (bg, fg) => ({
    display: "inline-block",
    padding: "0.15rem 0.55rem",
    borderRadius: 6,
    fontSize: "0.72rem",
    fontWeight: 600,
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    background: bg,
    color: fg,
  }),
  tag: (color = "#888") => ({
    display: "inline-block",
    background: `${color}15`,
    color,
    padding: "0.2rem 0.55rem",
    borderRadius: 6,
    margin: "0.15rem",
    fontSize: "0.78rem",
    wordBreak: "break-all",
    border: `1px solid ${color}25`,
  }),
  tabs: { display: "flex", gap: "0.25rem", marginBottom: "1rem" },
  tab: (active) => ({
    padding: "0.5rem 1rem",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.82rem",
    background: active ? "#fff" : "transparent",
    color: active ? "#000" : "#888",
    border: active ? "none" : "1px solid #333",
    letterSpacing: "0.02em",
  }),
  meta: { fontSize: "0.8rem", color: "#666" },
  error: {
    background: "rgba(239,68,68,0.1)",
    color: "#ef4444",
    padding: "0.75rem 1rem",
    borderRadius: 8,
    marginBottom: "1rem",
    fontSize: "0.85rem",
    border: "1px solid rgba(239,68,68,0.2)",
  },
  success: {
    background: "rgba(34,197,94,0.1)",
    color: "#22c55e",
    padding: "0.75rem 1rem",
    borderRadius: 8,
    marginBottom: "1rem",
    fontSize: "0.85rem",
    border: "1px solid rgba(34,197,94,0.2)",
  },
  guide: {
    background: "rgba(255,255,255,0.03)",
    border: "1px solid #2a2a2a",
    borderRadius: 10,
    padding: "1.25rem",
    marginBottom: "1rem",
  },
  guideTitle: { fontSize: "0.9rem", fontWeight: 600, color: "#aaa", marginBottom: "0.75rem", letterSpacing: "0.03em", textTransform: "uppercase" },
  guideStep: { display: "flex", gap: "0.75rem", marginBottom: "0.6rem", fontSize: "0.85rem", color: "#999" },
  guideNumber: {
    background: "#333",
    color: "#ccc",
    borderRadius: "50%",
    width: 22,
    height: 22,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.7rem",
    fontWeight: 700,
    flexShrink: 0,
  },
  guideToggle: { background: "none", border: "none", color: "#666", cursor: "pointer", fontSize: "0.8rem", fontWeight: 600, padding: 0 },
  modal: {
    position: "fixed",
    top: 0, left: 0, right: 0, bottom: 0,
    background: "rgba(0,0,0,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    backdropFilter: "blur(4px)",
  },
  modalContent: {
    background: "#1a1a1a",
    border: "1px solid #2a2a2a",
    borderRadius: 12,
    padding: "2rem",
    maxWidth: 650,
    width: "90%",
    maxHeight: "85vh",
    overflowY: "auto",
    color: "#e5e5e5",
  },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.75rem", marginBottom: "1rem" },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "0.75rem", marginBottom: "1rem" },
  link: { display: "block", color: "#888", fontSize: "0.78rem", wordBreak: "break-all", marginBottom: "0.2rem", textDecoration: "none" },
  sectionTitle: { fontSize: "0.85rem", fontWeight: 600, marginBottom: "0.5rem", color: "#aaa", textTransform: "uppercase", letterSpacing: "0.05em" },
  row: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.5rem 0", borderBottom: "1px solid #222" },
  pageTitle: { fontSize: "1.4rem", fontWeight: 700, color: "#fff", margin: 0, letterSpacing: "-0.02em" },
};

export default T;
